# ⚠️ AUTO-GENERATED by Sufleur CLI — do not edit manually
# Generated at: <normalised>
#
# Runtime peer dependencies (install in your project):
#   pip install chevron
#   pip install pydantic

from __future__ import annotations

import warnings
from typing import Any, Literal, TypedDict, overload, Optional, Union
from typing_extensions import NotRequired

import chevron
import json
import re
from pydantic import BaseModel, ValidationError

# ─── Types ────────────────────────────────────────────────────────────────────


class PromptOutput(TypedDict):
    prompt: str


# ─── TypedDicts for @acme/alpha-draft ────────────────────────────────────────────────


class _AcmeAlphaDraft_GreetingInput_User(TypedDict):
    age: NotRequired[Optional[int]]
    name: str
    """User's name"""


class AcmeAlphaDraft_GreetingInput(TypedDict):
    nickname: NotRequired[Optional[str]]
    tags: NotRequired[Optional[list[str]]]
    tone: NotRequired[Optional[str]]
    user: _AcmeAlphaDraft_GreetingInput_User


class _AcmeAlphaDraftMetadata(TypedDict):
    version: str

# ─── TypedDicts for @acme/beta-published ────────────────────────────────────────────────


class AcmeBetaPublished_ClassifyInput(TypedDict):
    text: str


class _AcmeBetaPublishedMetadata(TypedDict):
    model: str
    retries: int
    streaming: bool
    temperature: float
    outputSchema: dict[str, Any]
    modelConfig: dict[str, Any]
    version: str

# ─── TypedDicts for @acme/delta-escapes ────────────────────────────────────────────────


class AcmeDeltaEscapes_TrickyInput(TypedDict):
    weird: NotRequired[Optional[str]]
    """closes a comment */ here"""


class _AcmeDeltaEscapesMetadata(TypedDict):
    version: str

# ─── TypedDicts for @acme/gamma-bare ────────────────────────────────────────────────


class _AcmeGammaBareMetadata(TypedDict):
    version: str

# ─── Output Models ────────────────────────────────────────────────────────────


class AcmeBetaPublishedOutput(BaseModel):
    id: int
    label: str
    ok: Optional[bool] = None
    score: Optional[float] = None


class _AcmeBetaPublishedParseSuccess(TypedDict):
    data: AcmeBetaPublishedOutput
    success: Literal[True]


class ParseFailure(TypedDict):
    error: str
    code: Literal["fence-extraction", "json-parse", "schema-validation"]
    success: Literal[False]

# ─── Prompt Name Literal ─────────────────────────────────────────────────────

PromptName = Literal["@acme/alpha-draft", "@acme/beta-published", "@acme/delta-escapes", "@acme/gamma-bare"]

# ─── Templates ────────────────────────────────────────────────────────────────

_templates: dict[str, dict[str, str]] = {
    "@acme/alpha-draft": {
        "fallback": "No name given.",
        "greeting": "Hi {{user.name}}!\n{{#tags}}\n- {{.}}\n{{/tags}}\n{{>signature}}",
    },
    "@acme/beta-published": {
        "classify": "Classify this.\n\n{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"Unique ID\",\n      \"type\": \"integer\"\n    },\n    \"label\": {\n      \"minLength\": 1,\n      \"type\": \"string\"\n    },\n    \"ok\": {\n      \"type\": \"boolean\"\n    },\n    \"score\": {\n      \"type\": \"number\"\n    }\n  },\n  \"required\": [\n    \"id\",\n    \"label\"\n  ],\n  \"title\": \"Result\",\n  \"type\": \"object\"\n}",
    },
    "@acme/delta-escapes": {
        "tricky": "A backtick ` and a ${interpolation} and a backslash \\ walk into a bar.",
    },
    "@acme/gamma-bare": {
        "plain": "Nothing to see here.",
    },
}

# ─── Partials ─────────────────────────────────────────────────────────────────

_partials: dict[str, dict[str, str]] = {
    "@acme/alpha-draft": {
        "footer": "Sent by Sufleur.",
        "signature": "— The {{team}} team",
    },
    "@acme/beta-published": {
    },
    "@acme/delta-escapes": {
    },
    "@acme/gamma-bare": {
    },
}

# ─── Metadata ─────────────────────────────────────────────────────────────────
# Note: modelConfig.parameters keys are camelCase (matching the platform API);
# adapt them to your target SDK's parameter naming if needed.

_metadata: dict[str, dict[str, Any]] = {
    "@acme/alpha-draft": {
        "version": "0.3.0",
    },
    "@acme/beta-published": {
        "model": "gpt-4o",
        "retries": 3,
        "streaming": True,
        "temperature": 0.7,
        "outputSchema": json.loads('{"properties":{"id":{"description":"Unique ID","type":"integer"},"label":{"minLength":1,"type":"string"},"ok":{"type":"boolean"},"score":{"type":"number"}},"required":["id","label"],"title":"Result","type":"object"}'),
        "version": "2.1.0",
        "modelConfig": json.loads('{\n  "model": "claude-sonnet-4-5",\n  "parameters": {\n    "temperature": 0.2\n  },\n  "provider": "anthropic"\n}'),
    },
    "@acme/delta-escapes": {
        "version": "1.0.1",
    },
    "@acme/gamma-bare": {
        "version": "1.0.0",
    },
}

_output_models: dict[str, type[BaseModel]] = {
    "@acme/beta-published": AcmeBetaPublishedOutput,
}


_fence_re = re.compile(r"```([a-zA-Z]*)\s*\n?([\s\S]*?)\n?\s*```")


def _extract_balanced_braces(s: str) -> str | None:
    obj_start = s.find("{")
    arr_start = s.find("[")
    if obj_start == -1 and arr_start == -1:
        return None
    if obj_start != -1 and (arr_start == -1 or obj_start < arr_start):
        start, opener, closer = obj_start, "{", "}"
    else:
        start, opener, closer = arr_start, "[", "]"
    depth = 0
    in_string = False
    escape = False
    for i in range(start, len(s)):
        c = s[i]
        if escape:
            escape = False
            continue
        if in_string and c == "\\":
            escape = True
            continue
        if c == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if c == opener:
            depth += 1
        elif c == closer:
            depth -= 1
            if depth == 0:
                return s[start:i + 1]
    return None


def _extract_json_candidate(raw: str) -> tuple[str, bool]:
    """Best-effort JSON extraction. Returns (candidate_text, found_fence)."""
    trimmed = raw.strip()
    fences = [
        (m.group(1).lower(), m.group(2).strip())
        for m in _fence_re.finditer(trimmed)
    ]
    if fences:
        json_fence = next((body for lang, body in fences if lang == "json"), None)
        return (json_fence if json_fence is not None else fences[0][1], True)
    bare = _extract_balanced_braces(trimmed)
    if bare is not None:
        return (bare, False)
    return (trimmed, False)

# ─── Draft Prompts ────────────────────────────────────────────────────────────

_draft_prompts: set[str] = {
    "@acme/alpha-draft",
}

# ─── Per-prompt result types ─────────────────────────────────────────────────


class _AcmeAlphaDraftResult:
    """Draft prompt with nested, optional and union inputs

    Version: 0.3.0
    """

    def __init__(self, templates: dict[str, str], partials: dict[str, str], metadata: _AcmeAlphaDraftMetadata) -> None:
        self._templates = templates
        self._partials = partials
        self.metadata = metadata

    @overload
    def render(self, entrypoint: Literal["fallback"], input: dict[str, Any]) -> PromptOutput: ...

    @overload
    def render(self, entrypoint: Literal["greeting"], input: AcmeAlphaDraft_GreetingInput) -> PromptOutput: ...

    def render(self, entrypoint: str, input: Any = None) -> PromptOutput:
        """Render the named entrypoint template with the given input."""
        template = self._templates.get(entrypoint)
        if template is None:
            raise KeyError(f'[sufleur] Unknown entrypoint "{entrypoint}" for prompt "@acme/alpha-draft"')
        return {"prompt": chevron.render(template, input or {}, partials_dict=self._partials)}


class _AcmeBetaPublishedResult:
    """Published prompt with an output schema and full metadata

    Version: 2.1.0
    """

    def __init__(self, templates: dict[str, str], partials: dict[str, str], metadata: _AcmeBetaPublishedMetadata) -> None:
        self._templates = templates
        self._partials = partials
        self.metadata = metadata

    @overload
    def render(self, entrypoint: Literal["classify"], input: AcmeBetaPublished_ClassifyInput) -> PromptOutput: ...

    def render(self, entrypoint: str, input: Any = None) -> PromptOutput:
        """Render the named entrypoint template with the given input."""
        template = self._templates.get(entrypoint)
        if template is None:
            raise KeyError(f'[sufleur] Unknown entrypoint "{entrypoint}" for prompt "@acme/beta-published"')
        return {"prompt": chevron.render(template, input or {}, partials_dict=self._partials)}

    def parse_output(self, raw: str) -> _AcmeBetaPublishedParseSuccess | ParseFailure:
        """Parse and validate LLM output against the output schema."""
        candidate, found_fence = _extract_json_candidate(raw)
        try:
            parsed = json.loads(candidate)
        except json.JSONDecodeError as e:
            code = "fence-extraction" if found_fence else "json-parse"
            return {"error": str(e), "code": code, "success": False}
        try:
            validated = AcmeBetaPublishedOutput.model_validate(parsed)
        except ValidationError as e:
            return {"error": str(e), "code": "schema-validation", "success": False}
        return {"data": validated, "success": True}


class _AcmeDeltaEscapesResult:
    """Ends a comment */ and quotes \"like this\"

    Version: 1.0.1
    """

    def __init__(self, templates: dict[str, str], partials: dict[str, str], metadata: _AcmeDeltaEscapesMetadata) -> None:
        self._templates = templates
        self._partials = partials
        self.metadata = metadata

    @overload
    def render(self, entrypoint: Literal["tricky"], input: AcmeDeltaEscapes_TrickyInput) -> PromptOutput: ...

    def render(self, entrypoint: str, input: Any = None) -> PromptOutput:
        """Render the named entrypoint template with the given input."""
        template = self._templates.get(entrypoint)
        if template is None:
            raise KeyError(f'[sufleur] Unknown entrypoint "{entrypoint}" for prompt "@acme/delta-escapes"')
        return {"prompt": chevron.render(template, input or {}, partials_dict=self._partials)}


class _AcmeGammaBareResult:

    def __init__(self, templates: dict[str, str], partials: dict[str, str], metadata: _AcmeGammaBareMetadata) -> None:
        self._templates = templates
        self._partials = partials
        self.metadata = metadata

    @overload
    def render(self, entrypoint: Literal["plain"], input: dict[str, Any]) -> PromptOutput: ...

    def render(self, entrypoint: str, input: Any = None) -> PromptOutput:
        """Render the named entrypoint template with the given input."""
        template = self._templates.get(entrypoint)
        if template is None:
            raise KeyError(f'[sufleur] Unknown entrypoint "{entrypoint}" for prompt "@acme/gamma-bare"')
        return {"prompt": chevron.render(template, input or {}, partials_dict=self._partials)}


# ─── Overloads + implementation ──────────────────────────────────────────────


@overload
def get_prompt(prompt_name: Literal["@acme/alpha-draft"]) -> _AcmeAlphaDraftResult: ...


@overload
def get_prompt(prompt_name: Literal["@acme/beta-published"]) -> _AcmeBetaPublishedResult: ...


@overload
def get_prompt(prompt_name: Literal["@acme/delta-escapes"]) -> _AcmeDeltaEscapesResult: ...


@overload
def get_prompt(prompt_name: Literal["@acme/gamma-bare"]) -> _AcmeGammaBareResult: ...


def get_prompt(prompt_name: PromptName) -> Any:
    """Get a type-safe prompt by name.

    Returns a result object with a `render(entrypoint, input)` method.
    """
    if prompt_name in _draft_prompts:
        warnings.warn(
            f'[sufleur] Warning: prompt "{prompt_name}" is a draft version',
            stacklevel=2,
        )

    templates = _templates[prompt_name]
    partials = _partials.get(prompt_name, {})
    metadata = _metadata[prompt_name]

    class _PromptResult:
        def __init__(self) -> None:
            self.metadata = metadata

        def render(self, entrypoint: str, input: Any = None) -> PromptOutput:
            template = templates.get(entrypoint)
            if template is None:
                raise KeyError(f'[sufleur] Unknown entrypoint "{entrypoint}" for prompt "{prompt_name}"')
            return {"prompt": chevron.render(template, input or {}, partials_dict=partials)}

        def parse_output(self, raw: str) -> dict[str, Any]:
            model = _output_models.get(prompt_name)
            if model is None:
                return {"error": f"No output schema for prompt \"{prompt_name}\"", "code": "schema-validation", "success": False}
            candidate, found_fence = _extract_json_candidate(raw)
            try:
                parsed = json.loads(candidate)
            except json.JSONDecodeError as e:
                code = "fence-extraction" if found_fence else "json-parse"
                return {"error": str(e), "code": code, "success": False}
            try:
                validated = model.model_validate(parsed)
            except ValidationError as e:
                return {"error": str(e), "code": "schema-validation", "success": False}
            return {"data": validated, "success": True}

    return _PromptResult()
