# ⚠️ AUTO-GENERATED by Sufleur CLI — do not edit manually
# Generated at: <normalised>
#
# Runtime peer dependencies (install in your project):
#   pip install chevron
#   pip install pydantic

from __future__ import annotations

import warnings
from typing import Any, Literal, TypedDict, overload, Optional, Union

import chevron
import json
import re
from pydantic import BaseModel, ValidationError

# ─── Types ────────────────────────────────────────────────────────────────────


class PromptOutput(TypedDict):
    prompt: str


# ─── TypedDicts for @app/daily-brief ────────────────────────────────────────────────


class AppDailyBrief_MainInput(TypedDict):
    topic: str


class _AppDailyBriefMetadata(TypedDict):
    version: str

# ─── TypedDicts for @app/plain ────────────────────────────────────────────────


class _AppPlainMetadata(TypedDict):
    version: str

# ─── TypedDicts for @app/research ────────────────────────────────────────────────


class _AppResearchMetadata(TypedDict):
    outputSchema: dict[str, Any]
    version: str

# ─── Output Models ────────────────────────────────────────────────────────────


class AppResearchOutput(BaseModel):
    summary: str


class _AppResearchParseSuccess(TypedDict):
    data: AppResearchOutput
    success: Literal[True]


class ParseFailure(TypedDict):
    error: str
    code: Literal["fence-extraction", "json-parse", "schema-validation"]
    success: Literal[False]

# ─── Prompt Name Literal ─────────────────────────────────────────────────────

PromptName = Literal["@app/daily-brief", "@app/plain", "@app/research"]

# ─── Templates ────────────────────────────────────────────────────────────────

_templates: dict[str, dict[str, str]] = {
    "@app/daily-brief": {
        "main": "Research {{topic}}.",
    },
    "@app/plain": {
        "main": "No tools here.",
    },
    "@app/research": {
        "main": "Summarise.",
    },
}

# ─── Partials ─────────────────────────────────────────────────────────────────

_partials: dict[str, dict[str, str]] = {
    "@app/daily-brief": {
    },
    "@app/plain": {
    },
    "@app/research": {
    },
}

# ─── Metadata ─────────────────────────────────────────────────────────────────
# Note: modelConfig.parameters keys are camelCase (matching the platform API);
# adapt them to your target SDK's parameter naming if needed.

_metadata: dict[str, dict[str, Any]] = {
    "@app/daily-brief": {
        "version": "1.0.0",
    },
    "@app/plain": {
        "version": "1.0.0",
    },
    "@app/research": {
        "outputSchema": json.loads('{"properties":{"summary":{"type":"string"}},"required":["summary"],"type":"object"}'),
        "version": "2.0.0",
    },
}

_output_models: dict[str, type[BaseModel]] = {
    "@app/research": AppResearchOutput,
}


_fence_re = re.compile(r"```([a-zA-Z]*)\s*\n?([\s\S]*?)\n?\s*```")


def _extract_balanced_braces(s: str) -> str | None:
    obj_start = s.find("{")
    arr_start = s.find("[")
    if obj_start == -1 and arr_start == -1:
        return None
    if obj_start != -1 and (arr_start == -1 or obj_start < arr_start):
        start, opener, closer = obj_start, "{", "}"
    else:
        start, opener, closer = arr_start, "[", "]"
    depth = 0
    in_string = False
    escape = False
    for i in range(start, len(s)):
        c = s[i]
        if escape:
            escape = False
            continue
        if in_string and c == "\\":
            escape = True
            continue
        if c == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if c == opener:
            depth += 1
        elif c == closer:
            depth -= 1
            if depth == 0:
                return s[start:i + 1]
    return None


def _extract_json_candidate(raw: str) -> tuple[str, bool]:
    """Best-effort JSON extraction. Returns (candidate_text, found_fence)."""
    trimmed = raw.strip()
    fences = [
        (m.group(1).lower(), m.group(2).strip())
        for m in _fence_re.finditer(trimmed)
    ]
    if fences:
        json_fence = next((body for lang, body in fences if lang == "json"), None)
        return (json_fence if json_fence is not None else fences[0][1], True)
    bare = _extract_balanced_braces(trimmed)
    if bare is not None:
        return (bare, False)
    return (trimmed, False)

# ─── Draft Prompts ────────────────────────────────────────────────────────────

_draft_prompts: set[str] = {
}

# ─── Per-prompt result types ─────────────────────────────────────────────────


class _AppDailyBriefResult:
    """Agentic prompt with tools

    Version: 1.0.0
    """

    def __init__(self, templates: dict[str, str], partials: dict[str, str], metadata: _AppDailyBriefMetadata) -> None:
        self._templates = templates
        self._partials = partials
        self.metadata = metadata

    @overload
    def render(self, entrypoint: Literal["main"], input: AppDailyBrief_MainInput) -> PromptOutput: ...

    def render(self, entrypoint: str, input: Any = None) -> PromptOutput:
        """Render the named entrypoint template with the given input."""
        template = self._templates.get(entrypoint)
        if template is None:
            raise KeyError(f'[sufleur] Unknown entrypoint "{entrypoint}" for prompt "@app/daily-brief"')
        return {"prompt": chevron.render(template, input or {}, partials_dict=self._partials)}


class _AppPlainResult:

    def __init__(self, templates: dict[str, str], partials: dict[str, str], metadata: _AppPlainMetadata) -> None:
        self._templates = templates
        self._partials = partials
        self.metadata = metadata

    @overload
    def render(self, entrypoint: Literal["main"], input: dict[str, Any]) -> PromptOutput: ...

    def render(self, entrypoint: str, input: Any = None) -> PromptOutput:
        """Render the named entrypoint template with the given input."""
        template = self._templates.get(entrypoint)
        if template is None:
            raise KeyError(f'[sufleur] Unknown entrypoint "{entrypoint}" for prompt "@app/plain"')
        return {"prompt": chevron.render(template, input or {}, partials_dict=self._partials)}


class _AppResearchResult:

    def __init__(self, templates: dict[str, str], partials: dict[str, str], metadata: _AppResearchMetadata) -> None:
        self._templates = templates
        self._partials = partials
        self.metadata = metadata

    @overload
    def render(self, entrypoint: Literal["main"], input: dict[str, Any]) -> PromptOutput: ...

    def render(self, entrypoint: str, input: Any = None) -> PromptOutput:
        """Render the named entrypoint template with the given input."""
        template = self._templates.get(entrypoint)
        if template is None:
            raise KeyError(f'[sufleur] Unknown entrypoint "{entrypoint}" for prompt "@app/research"')
        return {"prompt": chevron.render(template, input or {}, partials_dict=self._partials)}

    def parse_output(self, raw: str) -> _AppResearchParseSuccess | ParseFailure:
        """Parse and validate LLM output against the output schema."""
        candidate, found_fence = _extract_json_candidate(raw)
        try:
            parsed = json.loads(candidate)
        except json.JSONDecodeError as e:
            code = "fence-extraction" if found_fence else "json-parse"
            return {"error": str(e), "code": code, "success": False}
        try:
            validated = AppResearchOutput.model_validate(parsed)
        except ValidationError as e:
            return {"error": str(e), "code": "schema-validation", "success": False}
        return {"data": validated, "success": True}


# ─── Overloads + implementation ──────────────────────────────────────────────


@overload
def get_prompt(prompt_name: Literal["@app/daily-brief"]) -> _AppDailyBriefResult: ...


@overload
def get_prompt(prompt_name: Literal["@app/plain"]) -> _AppPlainResult: ...


@overload
def get_prompt(prompt_name: Literal["@app/research"]) -> _AppResearchResult: ...


def get_prompt(prompt_name: PromptName) -> Any:
    """Get a type-safe prompt by name.

    Returns a result object with a `render(entrypoint, input)` method.
    """
    if prompt_name in _draft_prompts:
        warnings.warn(
            f'[sufleur] Warning: prompt "{prompt_name}" is a draft version',
            stacklevel=2,
        )

    templates = _templates[prompt_name]
    partials = _partials.get(prompt_name, {})
    metadata = _metadata[prompt_name]

    class _PromptResult:
        def __init__(self) -> None:
            self.metadata = metadata

        def render(self, entrypoint: str, input: Any = None) -> PromptOutput:
            template = templates.get(entrypoint)
            if template is None:
                raise KeyError(f'[sufleur] Unknown entrypoint "{entrypoint}" for prompt "{prompt_name}"')
            return {"prompt": chevron.render(template, input or {}, partials_dict=partials)}

        def parse_output(self, raw: str) -> dict[str, Any]:
            model = _output_models.get(prompt_name)
            if model is None:
                return {"error": f"No output schema for prompt \"{prompt_name}\"", "code": "schema-validation", "success": False}
            candidate, found_fence = _extract_json_candidate(raw)
            try:
                parsed = json.loads(candidate)
            except json.JSONDecodeError as e:
                code = "fence-extraction" if found_fence else "json-parse"
                return {"error": str(e), "code": code, "success": False}
            try:
                validated = model.model_validate(parsed)
            except ValidationError as e:
                return {"error": str(e), "code": "schema-validation", "success": False}
            return {"data": validated, "success": True}

    return _PromptResult()
