# ⚠️ AUTO-GENERATED by Sufleur CLI — do not edit manually
# Generated at: <normalised>
#
# Runtime peer dependencies (install in your project):
#   pip install chevron
#   pip install pydantic

from __future__ import annotations

import warnings
from typing import Any, Literal, TypedDict, overload, Optional, Union, Protocol

import chevron
import json
import re
from pydantic import BaseModel, ValidationError

# ─── Types ────────────────────────────────────────────────────────────────────


class PromptOutput(TypedDict):
    prompt: str


# ─── TypedDicts for @app/daily-brief ────────────────────────────────────────────────


class AppDailyBrief_MainInput(TypedDict):
    topic: str


class _AppDailyBriefMetadata(TypedDict):
    version: str

# ─── TypedDicts for @app/plain ────────────────────────────────────────────────


class _AppPlainMetadata(TypedDict):
    version: str

# ─── TypedDicts for @app/research ────────────────────────────────────────────────


class _AppResearchMetadata(TypedDict):
    outputSchema: dict[str, Any]
    version: str

# ─── Output Models ────────────────────────────────────────────────────────────


class AppResearchOutput(BaseModel):
    summary: str


class _AppResearchParseSuccess(TypedDict):
    data: AppResearchOutput
    success: Literal[True]


class ParseFailure(TypedDict):
    error: str
    code: Literal["fence-extraction", "json-parse", "schema-validation"]
    success: Literal[False]

# ─── Prompt Name Literal ─────────────────────────────────────────────────────

PromptName = Literal["@app/daily-brief", "@app/plain", "@app/research"]

# ─── Templates ────────────────────────────────────────────────────────────────

_templates: dict[str, dict[str, str]] = {
    "@app/daily-brief": {
        "main": "Research {{topic}}.",
    },
    "@app/plain": {
        "main": "No tools here.",
    },
    "@app/research": {
        "main": "Summarise.",
    },
}

# ─── Partials ─────────────────────────────────────────────────────────────────

_partials: dict[str, dict[str, str]] = {
    "@app/daily-brief": {
    },
    "@app/plain": {
    },
    "@app/research": {
    },
}

# ─── Metadata ─────────────────────────────────────────────────────────────────
# Note: modelConfig.parameters keys are camelCase (matching the platform API);
# adapt them to your target SDK's parameter naming if needed.

_metadata: dict[str, dict[str, Any]] = {
    "@app/daily-brief": {
        "version": "1.0.0",
    },
    "@app/plain": {
        "version": "1.0.0",
    },
    "@app/research": {
        "outputSchema": json.loads('{"properties":{"summary":{"type":"string"}},"required":["summary"],"type":"object"}'),
        "version": "2.0.0",
    },
}

_output_models: dict[str, type[BaseModel]] = {
    "@app/research": AppResearchOutput,
}


_fence_re = re.compile(r"```([a-zA-Z]*)\s*\n?([\s\S]*?)\n?\s*```")


def _extract_balanced_braces(s: str) -> str | None:
    obj_start = s.find("{")
    arr_start = s.find("[")
    if obj_start == -1 and arr_start == -1:
        return None
    if obj_start != -1 and (arr_start == -1 or obj_start < arr_start):
        start, opener, closer = obj_start, "{", "}"
    else:
        start, opener, closer = arr_start, "[", "]"
    depth = 0
    in_string = False
    escape = False
    for i in range(start, len(s)):
        c = s[i]
        if escape:
            escape = False
            continue
        if in_string and c == "\\":
            escape = True
            continue
        if c == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if c == opener:
            depth += 1
        elif c == closer:
            depth -= 1
            if depth == 0:
                return s[start:i + 1]
    return None


def _extract_json_candidate(raw: str) -> tuple[str, bool]:
    """Best-effort JSON extraction. Returns (candidate_text, found_fence)."""
    trimmed = raw.strip()
    fences = [
        (m.group(1).lower(), m.group(2).strip())
        for m in _fence_re.finditer(trimmed)
    ]
    if fences:
        json_fence = next((body for lang, body in fences if lang == "json"), None)
        return (json_fence if json_fence is not None else fences[0][1], True)
    bare = _extract_balanced_braces(trimmed)
    if bare is not None:
        return (bare, False)
    return (trimmed, False)

# ─── Tool Contracts ───────────────────────────────────────────────────────────
#
# The trust boundary runs the opposite way from prompt I/O: a tool's arguments
# are written by the model, so they are validated at runtime, while a tool's
# result comes from your own code, so a static type is enough.


class AcmeFetchPageToolInput(BaseModel):
    url: str


class AcmeFetchPageTool(Protocol):
    """Implement this to bind @acme/fetch-page@draft."""

    def __call__(self, input: AcmeFetchPageToolInput) -> Any: ...


class VendorWebSearchToolV1_2_0Input(BaseModel):
    maxResults: Optional[int] = None
    query: str


class _VendorWebSearchToolV1_2_0Output_Results(TypedDict):
    title: str
    url: str

class VendorWebSearchToolV1_2_0Output(TypedDict):
    results: list[_VendorWebSearchToolV1_2_0Output_Results]

class VendorWebSearchToolV1_2_0(Protocol):
    """Implement this to bind @vendor/web-search@1.2.0."""

    def __call__(self, input: VendorWebSearchToolV1_2_0Input) -> VendorWebSearchToolV1_2_0Output: ...


class VendorWebSearchToolV2_0_0Input(BaseModel):
    maxResults: Optional[int] = None
    query: str


class _VendorWebSearchToolV2_0_0Output_Results(TypedDict):
    title: str
    url: str

class VendorWebSearchToolV2_0_0Output(TypedDict):
    results: list[_VendorWebSearchToolV2_0_0Output_Results]

class VendorWebSearchToolV2_0_0(Protocol):
    """Implement this to bind @vendor/web-search@2.0.0."""

    def __call__(self, input: VendorWebSearchToolV2_0_0Input) -> VendorWebSearchToolV2_0_0Output: ...


class ToolExecutionError(Exception):
    """Raise from a tool implementation to report a failure the model may see."""


class _DispatchSuccess(TypedDict):
    content: str
    success: Literal[True]


class DispatchFailure(TypedDict):
    error: str
    code: Literal["unknown-tool", "input-validation", "execution"]
    success: Literal[False]

# Bindings per prompt, in functional syntax because wire names may be
# kebab-case, which is not a valid identifier. Every key is required — the model
# is offered every pinned tool, so an implementation for each has to be supplied.

AppDailyBriefTools = TypedDict("AppDailyBriefTools", {
    "fetch-page": AcmeFetchPageTool,
    "web_search": VendorWebSearchToolV1_2_0,
})


AppResearchTools = TypedDict("AppResearchTools", {
    "search": VendorWebSearchToolV2_0_0,
})


# ─── Tool Definitions ─────────────────────────────────────────────────────────
#
# Provider-neutral {name, description, input_schema}; adapt them if your SDK's
# tool format differs.

_tool_defs: dict[str, list[dict[str, Any]]] = {
    "@app/daily-brief": json.loads('[{"description":"Fetches a page.","input_schema":{"properties":{"url":{"type":"string"}},"required":["url"],"type":"object"},"name":"fetch-page"},{"description":"Searches the web.\\n\\nReturns JSON matching: {\\"properties\\":{\\"results\\":{\\"items\\":{\\"properties\\":{\\"title\\":{\\"type\\":\\"string\\"},\\"url\\":{\\"type\\":\\"string\\"}},\\"required\\":[\\"title\\",\\"url\\"],\\"type\\":\\"object\\"},\\"type\\":\\"array\\"}},\\"required\\":[\\"results\\"],\\"type\\":\\"object\\"}","input_schema":{"properties":{"maxResults":{"type":"integer"},"query":{"description":"What to search for","type":"string"}},"required":["query"],"type":"object"},"name":"web_search"}]'),
    "@app/research": json.loads('[{"description":"Searches the web, v2.\\n\\nReturns JSON matching: {\\"properties\\":{\\"results\\":{\\"items\\":{\\"properties\\":{\\"title\\":{\\"type\\":\\"string\\"},\\"url\\":{\\"type\\":\\"string\\"}},\\"required\\":[\\"title\\",\\"url\\"],\\"type\\":\\"object\\"},\\"type\\":\\"array\\"}},\\"required\\":[\\"results\\"],\\"type\\":\\"object\\"}","input_schema":{"properties":{"maxResults":{"type":"integer"},"query":{"description":"What to search for","type":"string"}},"required":["query"],"type":"object"},"name":"search"}]'),
}

# Argument validators, looked up at dispatch time. The typed per-prompt classes
# below exist for the type checker; get_prompt returns the dynamic result object,
# so this is what actually validates what the model sent.
_tool_input_models: dict[str, dict[str, type[BaseModel]]] = {
    "@app/daily-brief": {
        "fetch-page": AcmeFetchPageToolInput,
        "web_search": VendorWebSearchToolV1_2_0Input,
    },
    "@app/research": {
        "search": VendorWebSearchToolV2_0_0Input,
    },
}

# Pins on unpublished tool versions: the contract can still change under you.
_draft_tools: dict[str, list[str]] = {
    "@app/daily-brief": ["fetch-page"],
}

# ─── Draft Prompts ────────────────────────────────────────────────────────────


# No draft prompts installed. Spelled set() rather than {}, which is a dict.
_draft_prompts: set[str] = set()

# ─── Per-prompt result types ─────────────────────────────────────────────────


class _AppDailyBriefResult:
    """Agentic prompt with tools

    Version: 1.0.0
    """

    def __init__(self, templates: dict[str, str], partials: dict[str, str], metadata: _AppDailyBriefMetadata) -> None:
        self._templates = templates
        self._partials = partials
        self.metadata = metadata

    @overload
    def render(self, entrypoint: Literal["main"], input: AppDailyBrief_MainInput) -> PromptOutput: ...

    def render(self, entrypoint: str, input: Any = None) -> PromptOutput:
        """Render the named entrypoint template with the given input."""
        template = self._templates.get(entrypoint)
        if template is None:
            raise KeyError(f'[sufleur] Unknown entrypoint "{entrypoint}" for prompt "@app/daily-brief"')
        return {"prompt": chevron.render(template, input or {}, partials_dict=self._partials)}

    def tool_defs(self) -> list[dict[str, Any]]:
        """Provider-neutral definitions for every tool this prompt pins."""
        return list(_tool_defs["@app/daily-brief"])

    def dispatch_tool(
        self, name: str, raw_input: Any, tools: AppDailyBriefTools
    ) -> _DispatchSuccess | DispatchFailure:
        """Validate the model's arguments and invoke the bound implementation.

        Deliberately not a loop: call it once per tool_use block the model emits.
        """
        if name == "fetch-page":
            try:
                fetch_page_input = AcmeFetchPageToolInput.model_validate(raw_input)
            except ValidationError as e:
                return {"error": str(e), "code": "input-validation", "success": False}
            try:
                fetch_page_output = tools["fetch-page"](fetch_page_input)
            except ToolExecutionError as e:
                # Only ToolExecutionError is reported back to the model; anything
                # else is a bug in the implementation and keeps its traceback.
                return {"error": str(e), "code": "execution", "success": False}
            return {"content": json.dumps(fetch_page_output), "success": True}
        if name == "web_search":
            try:
                web_search_input = VendorWebSearchToolV1_2_0Input.model_validate(raw_input)
            except ValidationError as e:
                return {"error": str(e), "code": "input-validation", "success": False}
            try:
                web_search_output = tools["web_search"](web_search_input)
            except ToolExecutionError as e:
                # Only ToolExecutionError is reported back to the model; anything
                # else is a bug in the implementation and keeps its traceback.
                return {"error": str(e), "code": "execution", "success": False}
            return {"content": json.dumps(web_search_output), "success": True}
        return {
            "error": f'Unknown tool "{name}" for prompt "@app/daily-brief"',
            "code": "unknown-tool",
            "success": False,
        }


class _AppPlainResult:

    def __init__(self, templates: dict[str, str], partials: dict[str, str], metadata: _AppPlainMetadata) -> None:
        self._templates = templates
        self._partials = partials
        self.metadata = metadata

    @overload
    def render(self, entrypoint: Literal["main"], input: dict[str, Any]) -> PromptOutput: ...

    def render(self, entrypoint: str, input: Any = None) -> PromptOutput:
        """Render the named entrypoint template with the given input."""
        template = self._templates.get(entrypoint)
        if template is None:
            raise KeyError(f'[sufleur] Unknown entrypoint "{entrypoint}" for prompt "@app/plain"')
        return {"prompt": chevron.render(template, input or {}, partials_dict=self._partials)}


class _AppResearchResult:

    def __init__(self, templates: dict[str, str], partials: dict[str, str], metadata: _AppResearchMetadata) -> None:
        self._templates = templates
        self._partials = partials
        self.metadata = metadata

    @overload
    def render(self, entrypoint: Literal["main"], input: dict[str, Any]) -> PromptOutput: ...

    def render(self, entrypoint: str, input: Any = None) -> PromptOutput:
        """Render the named entrypoint template with the given input."""
        template = self._templates.get(entrypoint)
        if template is None:
            raise KeyError(f'[sufleur] Unknown entrypoint "{entrypoint}" for prompt "@app/research"')
        return {"prompt": chevron.render(template, input or {}, partials_dict=self._partials)}

    def parse_output(self, raw: str) -> _AppResearchParseSuccess | ParseFailure:
        """Parse and validate LLM output against the output schema."""
        candidate, found_fence = _extract_json_candidate(raw)
        try:
            parsed = json.loads(candidate)
        except json.JSONDecodeError as e:
            code = "fence-extraction" if found_fence else "json-parse"
            return {"error": str(e), "code": code, "success": False}
        try:
            validated = AppResearchOutput.model_validate(parsed)
        except ValidationError as e:
            return {"error": str(e), "code": "schema-validation", "success": False}
        return {"data": validated, "success": True}

    def tool_defs(self) -> list[dict[str, Any]]:
        """Provider-neutral definitions for every tool this prompt pins."""
        return list(_tool_defs["@app/research"])

    def dispatch_tool(
        self, name: str, raw_input: Any, tools: AppResearchTools
    ) -> _DispatchSuccess | DispatchFailure:
        """Validate the model's arguments and invoke the bound implementation.

        Deliberately not a loop: call it once per tool_use block the model emits.
        """
        if name == "search":
            try:
                search_input = VendorWebSearchToolV2_0_0Input.model_validate(raw_input)
            except ValidationError as e:
                return {"error": str(e), "code": "input-validation", "success": False}
            try:
                search_output = tools["search"](search_input)
            except ToolExecutionError as e:
                # Only ToolExecutionError is reported back to the model; anything
                # else is a bug in the implementation and keeps its traceback.
                return {"error": str(e), "code": "execution", "success": False}
            return {"content": json.dumps(search_output), "success": True}
        return {
            "error": f'Unknown tool "{name}" for prompt "@app/research"',
            "code": "unknown-tool",
            "success": False,
        }


# ─── Overloads + implementation ──────────────────────────────────────────────


@overload
def get_prompt(prompt_name: Literal["@app/daily-brief"]) -> _AppDailyBriefResult: ...


@overload
def get_prompt(prompt_name: Literal["@app/plain"]) -> _AppPlainResult: ...


@overload
def get_prompt(prompt_name: Literal["@app/research"]) -> _AppResearchResult: ...


def get_prompt(prompt_name: PromptName) -> Any:
    """Get a type-safe prompt by name.

    Returns a result object with a `render(entrypoint, input)` method.
    """
    if prompt_name in _draft_prompts:
        warnings.warn(
            f'[sufleur] Warning: prompt "{prompt_name}" is a draft version',
            stacklevel=2,
        )
    _pinned_drafts = _draft_tools.get(prompt_name)
    if _pinned_drafts:
        warnings.warn(
            f'[sufleur] Warning: prompt "{prompt_name}" pins draft tool version(s): '
            + ", ".join(_pinned_drafts),
            stacklevel=2,
        )

    templates = _templates[prompt_name]
    partials = _partials.get(prompt_name, {})
    metadata = _metadata[prompt_name]

    class _PromptResult:
        def __init__(self) -> None:
            self.metadata = metadata

        def render(self, entrypoint: str, input: Any = None) -> PromptOutput:
            template = templates.get(entrypoint)
            if template is None:
                raise KeyError(f'[sufleur] Unknown entrypoint "{entrypoint}" for prompt "{prompt_name}"')
            return {"prompt": chevron.render(template, input or {}, partials_dict=partials)}

        def parse_output(self, raw: str) -> dict[str, Any]:
            model = _output_models.get(prompt_name)
            if model is None:
                return {"error": f"No output schema for prompt \"{prompt_name}\"", "code": "schema-validation", "success": False}
            candidate, found_fence = _extract_json_candidate(raw)
            try:
                parsed = json.loads(candidate)
            except json.JSONDecodeError as e:
                code = "fence-extraction" if found_fence else "json-parse"
                return {"error": str(e), "code": code, "success": False}
            try:
                validated = model.model_validate(parsed)
            except ValidationError as e:
                return {"error": str(e), "code": "schema-validation", "success": False}
            return {"data": validated, "success": True}

        def tool_defs(self) -> list[dict[str, Any]]:
            return list(_tool_defs.get(prompt_name, []))

        def dispatch_tool(self, name: str, raw_input: Any, tools: Any) -> dict[str, Any]:
            model = _tool_input_models.get(prompt_name, {}).get(name)
            impl = tools.get(name) if isinstance(tools, dict) else None
            if model is None or impl is None:
                return {
                    "error": f'Unknown tool "{name}" for prompt "{prompt_name}"',
                    "code": "unknown-tool",
                    "success": False,
                }
            try:
                validated = model.model_validate(raw_input)
            except ValidationError as e:
                return {"error": str(e), "code": "input-validation", "success": False}
            try:
                output = impl(validated)
            except ToolExecutionError as e:
                # Only ToolExecutionError is reported back to the model; anything
                # else is a bug in the implementation and keeps its traceback.
                return {"error": str(e), "code": "execution", "success": False}
            return {"content": json.dumps(output), "success": True}

    return _PromptResult()
