// ⚠️ AUTO-GENERATED by Sufleur CLI — do not edit manually
// Generated at: <normalised>
//
// Runtime peer dependencies (install in your project):
//   npm i mustache
//   npm i -D @types/mustache
//   npm i zod

import Mustache from 'mustache';
import { z } from 'zod';

// ─── Types ────────────────────────────────────────────────────────────────────

interface PromptOutput {
  prompt: string;
}

export type AcmeAlphaDraft_GreetingInput = {
  nickname?: string | null;
  tags?: string[] | null;
  tone?: string | null;
  user: {
    age?: number | null;
    /** User's name */
    name: string;
  };
};

export type AcmeBetaPublished_ClassifyInput = {
  text: string;
};

export type AcmeDeltaEscapes_TrickyInput = {
  /** closes a comment *\/ here */
  weird?: string | null;
};

// ─── Output Schemas ──────────────────────────────────────────────────────────

export const AcmeBetaPublishedOutputSchema = z.object({
  id: z.number().int(),
  label: z.string(),
  ok: z.boolean().optional(),
  score: z.number().optional(),
});

export type AcmeBetaPublishedOutput = z.infer<typeof AcmeBetaPublishedOutputSchema>;

export type ParseResult<T> =
  | { success: true; data: T }
  | { success: false; error: string; code: 'fence-extraction' | 'json-parse' | 'schema-validation' };

export interface OutputMapping {
  '@acme/alpha-draft': never;
  '@acme/beta-published': AcmeBetaPublishedOutput;
  '@acme/delta-escapes': never;
  '@acme/gamma-bare': never;
}

// ─── Prompt Name Union ────────────────────────────────────────────────────────

export type PromptName = | '@acme/alpha-draft' | '@acme/beta-published' | '@acme/delta-escapes' | '@acme/gamma-bare';

// ─── Entrypoint Mapping ───────────────────────────────────────────────────────
//
// For each prompt, lists its entrypoint files and the input type required to
// render each one. Drives type narrowing for `render(entrypoint, input)`.
// Entrypoints with an empty object schema accept `Record<string, unknown>`;
// entrypoints with no input schema at all accept `Record<string, never>`.
// Callers pass `{}` for either case.

export interface EntrypointMapping {
  '@acme/alpha-draft': {
    'fallback': Record<string, never>;
    'greeting': AcmeAlphaDraft_GreetingInput;
  };
  '@acme/beta-published': {
    'classify': AcmeBetaPublished_ClassifyInput;
  };
  '@acme/delta-escapes': {
    'tricky': AcmeDeltaEscapes_TrickyInput;
  };
  '@acme/gamma-bare': {
    'plain': Record<string, never>;
  };
}

// ─── Templates ────────────────────────────────────────────────────────────────

const _templates: Record<PromptName, Record<string, string>> = {
  '@acme/alpha-draft': {
    'fallback': `No name given.`,
    'greeting': `Hi {{user.name}}!
{{#tags}}
- {{.}}
{{/tags}}
{{>signature}}`,
  },
  '@acme/beta-published': {
    'classify': `Classify this.

{
  "properties": {
    "id": {
      "description": "Unique ID",
      "type": "integer"
    },
    "label": {
      "minLength": 1,
      "type": "string"
    },
    "ok": {
      "type": "boolean"
    },
    "score": {
      "type": "number"
    }
  },
  "required": [
    "id",
    "label"
  ],
  "title": "Result",
  "type": "object"
}`,
  },
  '@acme/delta-escapes': {
    'tricky': `A backtick \` and a \${interpolation} and a backslash \\ walk into a bar.`,
  },
  '@acme/gamma-bare': {
    'plain': `Nothing to see here.`,
  },
};

// ─── Partials ─────────────────────────────────────────────────────────────────

const _partials: Record<PromptName, Record<string, string>> = {
  '@acme/alpha-draft': {
    'footer': `Sent by Sufleur.`,
    'signature': `— The {{team}} team`,
  },
  '@acme/beta-published': {
  },
  '@acme/delta-escapes': {
  },
  '@acme/gamma-bare': {
  },
};

// ─── Metadata ─────────────────────────────────────────────────────────────────

export const _metadata = {
  '@acme/alpha-draft': {
    version: '0.3.0',
  },
  '@acme/beta-published': {
    model: 'gpt-4o',
    retries: 3,
    streaming: true,
    temperature: 0.7,
    version: '2.1.0',
    modelConfig: {
  "model": "claude-sonnet-4-5",
  "parameters": {
    "temperature": 0.2
  },
  "provider": "anthropic"
},
    outputSchema: {"properties":{"id":{"description":"Unique ID","type":"integer"},"label":{"minLength":1,"type":"string"},"ok":{"type":"boolean"},"score":{"type":"number"}},"required":["id","label"],"title":"Result","type":"object"},
  },
  '@acme/delta-escapes': {
    version: '1.0.1',
  },
  '@acme/gamma-bare': {
    version: '1.0.0',
  },
} as const;

const _outputSchemas: Partial<Record<PromptName, z.ZodType>> = {
  '@acme/beta-published': AcmeBetaPublishedOutputSchema,
};

const _fenceRe = /```([a-zA-Z]*)\s*\n?([\s\S]*?)\n?\s*```/g;

const _extractBalancedBraces = (s: string): string | null => {
  const objStart = s.indexOf('{');
  const arrStart = s.indexOf('[');
  let start = -1;
  let opener = '';
  let closer = '';
  if (objStart !== -1 && (arrStart === -1 || objStart < arrStart)) {
    start = objStart; opener = '{'; closer = '}';
  } else if (arrStart !== -1) {
    start = arrStart; opener = '['; closer = ']';
  } else {
    return null;
  }
  let depth = 0;
  let inString = false;
  let escape = false;
  for (let i = start; i < s.length; i++) {
    const c = s.charAt(i);
    if (escape) { escape = false; continue; }
    if (inString && c === '\\') { escape = true; continue; }
    if (c === '"') { inString = !inString; continue; }
    if (inString) continue;
    if (c === opener) depth++;
    else if (c === closer) {
      depth--;
      if (depth === 0) return s.slice(start, i + 1);
    }
  }
  return null;
};

const _extractJsonCandidate = (raw: string): { text: string; foundFence: boolean } => {
  const trimmed = raw.trim();
  const fences: Array<{ lang: string; body: string }> = [];
  _fenceRe.lastIndex = 0;
  let m: RegExpExecArray | null;
  while ((m = _fenceRe.exec(trimmed)) !== null) {
    fences.push({ lang: (m[1] ?? '').toLowerCase(), body: (m[2] ?? '').trim() });
  }
  if (fences.length > 0) {
    const jsonFence = fences.find(f => f.lang === 'json');
    const chosen = jsonFence ?? fences[0]!;
    return { text: chosen.body, foundFence: true };
  }
  const bare = _extractBalancedBraces(trimmed);
  if (bare !== null) return { text: bare, foundFence: false };
  return { text: trimmed, foundFence: false };
};

// ─── Draft Prompts ────────────────────────────────────────────────────────────

const _draftPrompts: Set<string> = new Set([
  '@acme/alpha-draft',
]);

// ─── getPrompt ────────────────────────────────────────────────────────────────

type PromptResult<N extends PromptName> = {
  render: <E extends keyof EntrypointMapping[N] & string>(
    entrypoint: E,
    input: EntrypointMapping[N][E],
  ) => PromptOutput;
  metadata: (typeof _metadata)[N];
} & (OutputMapping[N] extends never ? {} : {
  parseOutput(raw: string): ParseResult<OutputMapping[N]>;
});

// Per-prompt overloads carry each prompt's own JSDoc (description + version)
// so it surfaces on hover at the `getPrompt("name")` call site — the generic
// implementation signature below is erased at the boundary and cannot carry
// per-prompt docs on its own.

/**
 * Draft prompt with nested, optional and union inputs
 * @version 0.3.0
 */
export function getPrompt(promptName: '@acme/alpha-draft'): PromptResult<'@acme/alpha-draft'>;

/**
 * Published prompt with an output schema and full metadata
 * @version 2.1.0
 */
export function getPrompt(promptName: '@acme/beta-published'): PromptResult<'@acme/beta-published'>;

/**
 * Ends a comment *\/ and quotes "like this"
 * @version 1.0.1
 */
export function getPrompt(promptName: '@acme/delta-escapes'): PromptResult<'@acme/delta-escapes'>;

export function getPrompt(promptName: '@acme/gamma-bare'): PromptResult<'@acme/gamma-bare'>;
// Generic overload — required so callers holding a dynamic PromptName
// (e.g. a variable from iterating prompt names) can still resolve a call;
// without it, only the literal per-prompt overloads above are externally
// callable and a union-typed argument fails overload resolution. TS prefers
// the more specific literal overload when the argument is itself a literal,
// so per-prompt hover docs are unaffected.
export function getPrompt<N extends PromptName>(promptName: N): PromptResult<N>;
export function getPrompt<N extends PromptName>(promptName: N): PromptResult<N> {
  if (_draftPrompts.has(promptName)) {
    console.warn(`[sufleur] Warning: prompt "${promptName}" is a draft version`);
  }

  const templates = _templates[promptName];
  const partials = _partials[promptName] ?? {};

  const render = <E extends keyof EntrypointMapping[N] & string>(
    entrypoint: E,
    input: EntrypointMapping[N][E],
  ): PromptOutput => {
    const template = templates[entrypoint];
    if (template === undefined) {
      throw new Error(`[sufleur] Unknown entrypoint "${entrypoint}" for prompt "${promptName}"`);
    }
    return { prompt: Mustache.render(template, input ?? {}, partials) };
  };

  const metadata = _metadata[promptName];
  const schema = _outputSchemas[promptName];

  if (schema) {
    const parseOutput = (raw: string): ParseResult<OutputMapping[N]> => {
      const candidate = _extractJsonCandidate(raw);
      let parsed: unknown;
      try {
        parsed = JSON.parse(candidate.text);
      } catch (e: unknown) {
        const message = e instanceof Error ? e.message : String(e);
        return {
          success: false,
          error: message,
          code: candidate.foundFence ? 'fence-extraction' : 'json-parse',
        };
      }
      const validated = schema.safeParse(parsed);
      if (validated.success) {
        return { success: true, data: validated.data as OutputMapping[N] };
      }
      return { success: false, error: validated.error.message, code: 'schema-validation' };
    };
    return { render, metadata, parseOutput } as PromptResult<N>;
  }

  return { render, metadata } as PromptResult<N>;
}
