// ⚠️ AUTO-GENERATED by Sufleur CLI — do not edit manually
// Generated at: <normalised>
//
// Runtime peer dependencies (install in your project):
//   npm i mustache
//   npm i -D @types/mustache
//   npm i zod

import Mustache from 'mustache';
import { z } from 'zod';

// ─── Types ────────────────────────────────────────────────────────────────────

interface PromptOutput {
  prompt: string;
}

export type AppDailyBrief_MainInput = {
  topic: string;
};

// ─── Output Schemas ──────────────────────────────────────────────────────────

export const AppResearchOutputSchema = z.object({
  summary: z.string(),
});

export type AppResearchOutput = z.infer<typeof AppResearchOutputSchema>;

export type ParseResult<T> =
  | { success: true; data: T }
  | { success: false; error: string; code: 'fence-extraction' | 'json-parse' | 'schema-validation' };

export interface OutputMapping {
  '@app/daily-brief': never;
  '@app/plain': never;
  '@app/research': AppResearchOutput;
}

// ─── Tool Contracts ──────────────────────────────────────────────────────────
//
// The trust boundary runs the opposite way from prompt I/O: a tool's arguments
// are written by the model, so they are validated at runtime, while a tool's
// result comes from your own code, so a static type is enough.

export const AcmeFetchPageToolInputSchema = z.object({
  url: z.string(),
});

export type AcmeFetchPageToolInput = z.infer<typeof AcmeFetchPageToolInputSchema>;

export type AcmeFetchPageToolOutput = unknown;

export type AcmeFetchPageTool = (
  input: AcmeFetchPageToolInput,
) => Promise<AcmeFetchPageToolOutput> | AcmeFetchPageToolOutput;

export const VendorWebSearchToolV1_2_0InputSchema = z.object({
  maxResults: z.number().int().optional(),
  query: z.string(),
});

export type VendorWebSearchToolV1_2_0Input = z.infer<typeof VendorWebSearchToolV1_2_0InputSchema>;

export type VendorWebSearchToolV1_2_0Output = {
  results: ({
    title: string;
    url: string;
  })[];
};

export type VendorWebSearchToolV1_2_0 = (
  input: VendorWebSearchToolV1_2_0Input,
) => Promise<VendorWebSearchToolV1_2_0Output> | VendorWebSearchToolV1_2_0Output;

export const VendorWebSearchToolV2_0_0InputSchema = z.object({
  maxResults: z.number().int().optional(),
  query: z.string(),
});

export type VendorWebSearchToolV2_0_0Input = z.infer<typeof VendorWebSearchToolV2_0_0InputSchema>;

export type VendorWebSearchToolV2_0_0Output = {
  results: ({
    title: string;
    url: string;
  })[];
};

export type VendorWebSearchToolV2_0_0 = (
  input: VendorWebSearchToolV2_0_0Input,
) => Promise<VendorWebSearchToolV2_0_0Output> | VendorWebSearchToolV2_0_0Output;

/** Throw from a tool implementation to report a failure the model may see. */
export class ToolExecutionError extends Error {}

/** Provider-neutral tool definition; adapt it if your SDK's shape differs. */
export interface ToolDef {
  name: string;
  description: string;
  input_schema: Record<string, unknown>;
}

export type DispatchResult =
  | { success: true; content: string }
  | { success: false; error: string; code: 'unknown-tool' | 'input-validation' | 'execution' };

// Every pinned tool is required: the model is offered all of them, so an
// implementation for each one has to be supplied.
export interface ToolMapping {
  '@app/daily-brief': {
    'fetch-page': AcmeFetchPageTool;
    'web_search': VendorWebSearchToolV1_2_0;
  };
  '@app/plain': never;
  '@app/research': {
    'search': VendorWebSearchToolV2_0_0;
  };
}

// ─── Prompt Name Union ────────────────────────────────────────────────────────

export type PromptName = | '@app/daily-brief' | '@app/plain' | '@app/research';

// ─── Entrypoint Mapping ───────────────────────────────────────────────────────
//
// For each prompt, lists its entrypoint files and the input type required to
// render each one. Drives type narrowing for `render(entrypoint, input)`.
// Entrypoints with an empty object schema accept `Record<string, unknown>`;
// entrypoints with no input schema at all accept `Record<string, never>`.
// Callers pass `{}` for either case.

export interface EntrypointMapping {
  '@app/daily-brief': {
    'main': AppDailyBrief_MainInput;
  };
  '@app/plain': {
    'main': Record<string, never>;
  };
  '@app/research': {
    'main': Record<string, never>;
  };
}

// ─── Templates ────────────────────────────────────────────────────────────────

const _templates: Record<PromptName, Record<string, string>> = {
  '@app/daily-brief': {
    'main': `Research {{topic}}.`,
  },
  '@app/plain': {
    'main': `No tools here.`,
  },
  '@app/research': {
    'main': `Summarise.`,
  },
};

// ─── Partials ─────────────────────────────────────────────────────────────────

const _partials: Record<PromptName, Record<string, string>> = {
  '@app/daily-brief': {
  },
  '@app/plain': {
  },
  '@app/research': {
  },
};

// ─── Metadata ─────────────────────────────────────────────────────────────────

export const _metadata = {
  '@app/daily-brief': {
    version: '1.0.0',
  },
  '@app/plain': {
    version: '1.0.0',
  },
  '@app/research': {
    version: '2.0.0',
    outputSchema: {"properties":{"summary":{"type":"string"}},"required":["summary"],"type":"object"},
  },
} as const;

const _outputSchemas: Partial<Record<PromptName, z.ZodType>> = {
  '@app/research': AppResearchOutputSchema,
};

const _fenceRe = /```([a-zA-Z]*)\s*\n?([\s\S]*?)\n?\s*```/g;

const _extractBalancedBraces = (s: string): string | null => {
  const objStart = s.indexOf('{');
  const arrStart = s.indexOf('[');
  let start = -1;
  let opener = '';
  let closer = '';
  if (objStart !== -1 && (arrStart === -1 || objStart < arrStart)) {
    start = objStart; opener = '{'; closer = '}';
  } else if (arrStart !== -1) {
    start = arrStart; opener = '['; closer = ']';
  } else {
    return null;
  }
  let depth = 0;
  let inString = false;
  let escape = false;
  for (let i = start; i < s.length; i++) {
    const c = s.charAt(i);
    if (escape) { escape = false; continue; }
    if (inString && c === '\\') { escape = true; continue; }
    if (c === '"') { inString = !inString; continue; }
    if (inString) continue;
    if (c === opener) depth++;
    else if (c === closer) {
      depth--;
      if (depth === 0) return s.slice(start, i + 1);
    }
  }
  return null;
};

const _extractJsonCandidate = (raw: string): { text: string; foundFence: boolean } => {
  const trimmed = raw.trim();
  const fences: Array<{ lang: string; body: string }> = [];
  _fenceRe.lastIndex = 0;
  let m: RegExpExecArray | null;
  while ((m = _fenceRe.exec(trimmed)) !== null) {
    fences.push({ lang: (m[1] ?? '').toLowerCase(), body: (m[2] ?? '').trim() });
  }
  if (fences.length > 0) {
    const jsonFence = fences.find(f => f.lang === 'json');
    const chosen = jsonFence ?? fences[0]!;
    return { text: chosen.body, foundFence: true };
  }
  const bare = _extractBalancedBraces(trimmed);
  if (bare !== null) return { text: bare, foundFence: false };
  return { text: trimmed, foundFence: false };
};

// ─── Tool Definitions ─────────────────────────────────────────────────────────

const _toolDefs: Partial<Record<PromptName, readonly ToolDef[]>> = {
  '@app/daily-brief': [
    {
      "description": "Fetches a page.",
      "input_schema": {
        "properties": {
          "url": {
            "type": "string"
          }
        },
        "required": [
          "url"
        ],
        "type": "object"
      },
      "name": "fetch-page"
    },
    {
      "description": "Searches the web.\n\nReturns JSON matching: {\"properties\":{\"results\":{\"items\":{\"properties\":{\"title\":{\"type\":\"string\"},\"url\":{\"type\":\"string\"}},\"required\":[\"title\",\"url\"],\"type\":\"object\"},\"type\":\"array\"}},\"required\":[\"results\"],\"type\":\"object\"}",
      "input_schema": {
        "properties": {
          "maxResults": {
            "type": "integer"
          },
          "query": {
            "description": "What to search for",
            "type": "string"
          }
        },
        "required": [
          "query"
        ],
        "type": "object"
      },
      "name": "web_search"
    },
  ],
  '@app/research': [
    {
      "description": "Searches the web, v2.\n\nReturns JSON matching: {\"properties\":{\"results\":{\"items\":{\"properties\":{\"title\":{\"type\":\"string\"},\"url\":{\"type\":\"string\"}},\"required\":[\"title\",\"url\"],\"type\":\"object\"},\"type\":\"array\"}},\"required\":[\"results\"],\"type\":\"object\"}",
      "input_schema": {
        "properties": {
          "maxResults": {
            "type": "integer"
          },
          "query": {
            "description": "What to search for",
            "type": "string"
          }
        },
        "required": [
          "query"
        ],
        "type": "object"
      },
      "name": "search"
    },
  ],
};

const _toolInputSchemas: Partial<Record<PromptName, Record<string, z.ZodType>>> = {
  '@app/daily-brief': {
    'fetch-page': AcmeFetchPageToolInputSchema,
    'web_search': VendorWebSearchToolV1_2_0InputSchema,
  },
  '@app/research': {
    'search': VendorWebSearchToolV2_0_0InputSchema,
  },
};

// Pins on unpublished tool versions: the contract can still change under you.
const _draftTools: Partial<Record<PromptName, readonly string[]>> = {
  '@app/daily-brief': ['fetch-page'],
};

// ─── Draft Prompts ────────────────────────────────────────────────────────────

const _draftPrompts: Set<string> = new Set([
]);

// ─── getPrompt ────────────────────────────────────────────────────────────────

type PromptResult<N extends PromptName> = {
  render: <E extends keyof EntrypointMapping[N] & string>(
    entrypoint: E,
    input: EntrypointMapping[N][E],
  ) => PromptOutput;
  metadata: (typeof _metadata)[N];
} & (OutputMapping[N] extends never ? {} : {
  parseOutput(raw: string): ParseResult<OutputMapping[N]>;
}) & (ToolMapping[N] extends never ? {} : {
  toolDefs(): ToolDef[];
  dispatchTool(name: string, rawInput: unknown, tools: ToolMapping[N]): Promise<DispatchResult>;
});

// Per-prompt overloads carry each prompt's own JSDoc (description + version)
// so it surfaces on hover at the `getPrompt("name")` call site — the generic
// implementation signature below is erased at the boundary and cannot carry
// per-prompt docs on its own.

/**
 * Agentic prompt with tools
 * @version 1.0.0
 */
export function getPrompt(promptName: '@app/daily-brief'): PromptResult<'@app/daily-brief'>;

export function getPrompt(promptName: '@app/plain'): PromptResult<'@app/plain'>;

export function getPrompt(promptName: '@app/research'): PromptResult<'@app/research'>;
// Generic overload — required so callers holding a dynamic PromptName
// (e.g. a variable from iterating prompt names) can still resolve a call;
// without it, only the literal per-prompt overloads above are externally
// callable and a union-typed argument fails overload resolution. TS prefers
// the more specific literal overload when the argument is itself a literal,
// so per-prompt hover docs are unaffected.
export function getPrompt<N extends PromptName>(promptName: N): PromptResult<N>;
export function getPrompt<N extends PromptName>(promptName: N): PromptResult<N> {
  if (_draftPrompts.has(promptName)) {
    console.warn('[sufleur] Warning: prompt "' + promptName + '" is a draft version');
  }
  const draftPins = _draftTools[promptName];
  if (draftPins) {
    console.warn(
      '[sufleur] Warning: prompt "' + promptName + '" pins draft tool version(s): ' + draftPins.join(', '),
    );
  }

  const templates = _templates[promptName];
  const partials = _partials[promptName] ?? {};

  const render = <E extends keyof EntrypointMapping[N] & string>(
    entrypoint: E,
    input: EntrypointMapping[N][E],
  ): PromptOutput => {
    const template = templates[entrypoint];
    if (template === undefined) {
      throw new Error('[sufleur] Unknown entrypoint "' + entrypoint + '" for prompt "' + promptName + '"');
    }
    return { prompt: Mustache.render(template, input ?? {}, partials) };
  };

  const metadata = _metadata[promptName];
  const result: Record<string, unknown> = { render, metadata };

  const schema = _outputSchemas[promptName];
  if (schema) {
    result.parseOutput = (raw: string): ParseResult<OutputMapping[N]> => {
      const candidate = _extractJsonCandidate(raw);
      let parsed: unknown;
      try {
        parsed = JSON.parse(candidate.text);
      } catch (e: unknown) {
        const message = e instanceof Error ? e.message : String(e);
        return {
          success: false,
          error: message,
          code: candidate.foundFence ? 'fence-extraction' : 'json-parse',
        };
      }
      const validated = schema.safeParse(parsed);
      if (validated.success) {
        return { success: true, data: validated.data as OutputMapping[N] };
      }
      return { success: false, error: validated.error.message, code: 'schema-validation' };
    };
  }

  const defs = _toolDefs[promptName];
  const toolSchemas = _toolInputSchemas[promptName];
  if (defs && toolSchemas) {
    result.toolDefs = (): ToolDef[] => [...defs];

    // Validates the arguments the model produced, then calls your binding.
    // Deliberately not a loop: call it once per tool_use block.
    result.dispatchTool = async (
      name: string,
      rawInput: unknown,
      tools: ToolMapping[N],
    ): Promise<DispatchResult> => {
      const argSchema = toolSchemas[name];
      const impl = (tools as unknown as Record<string, ((input: never) => unknown) | undefined>)[name];
      if (argSchema === undefined || typeof impl !== 'function') {
        return {
          success: false,
          error: 'Unknown tool "' + name + '" for prompt "' + promptName + '"',
          code: 'unknown-tool',
        };
      }
      const parsed = argSchema.safeParse(rawInput);
      if (!parsed.success) {
        return { success: false, error: parsed.error.message, code: 'input-validation' };
      }
      try {
        const output = await impl(parsed.data as never);
        return { success: true, content: JSON.stringify(output) };
      } catch (e: unknown) {
        // Only ToolExecutionError is reported back to the model; anything else
        // is a bug in the implementation and keeps its stack.
        if (e instanceof ToolExecutionError) {
          return { success: false, error: e.message, code: 'execution' };
        }
        throw e;
      }
    };
  }

  return result as PromptResult<N>;
}
